### ISSUE TITLE
画像リンク切れについて

### ISSUE THREAD

**Issue by nodchip** [nodchip/QMAClone#757]
**Reported by                 on 16 Feb 2014 09:30 UTC**
いつもお世話になっております。

直接プレイに関わることではありませんが、
ここ1か月ほど「設定」欄の「画像リンク切れ」が表示されなくなっています。

お時間のある時にご確認お願いします。

**Comment by nodchip** [comment]
**Comment by nodchip on 17 Mar 2014 14:08 UTC**
以下、管理人用のメモです。

3 17, 2014 4:53:28 午後 tv.dyndns.kishibe.qmaclone.server.ImageManager$1 run
警告: ImageLinkの更新に失敗しました
tv.dyndns.kishibe.qmaclone.server.database.DatabaseException: java.sql.SQLException: java.net.MalformedURLException: no protocol:  height= Query: SELECT * FROM problem Parameters: [tv.dyndns.kishibe.qmaclone.server.database.DirectDatabase.processProblems(DirectDatabase.java:1243)
at tv.dyndns.kishibe.qmaclone.server.database.CachedDatabase.processProblems(CachedDatabase.java:814)
at tv.dyndns.kishibe.qmaclone.server.ImageManager.update(ImageManager.java:278)
at tv.dyndns.kishibe.qmaclone.server.ImageManager.access$0(ImageManager.java:274)
at tv.dyndns.kishibe.qmaclone.server.ImageManager$1.run(ImageManager.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.SQLException: java.net.MalformedURLException: no protocol:  height= Query: SELECT * FROM problem Parameters: [](]
at)
at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:350)
at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:306)
at tv.dyndns.kishibe.qmaclone.server.database.DirectDatabase.processProblems(DirectDatabase.java:1221)
... 11 more

**Comment by nodchip** [comment]
**Modified by nodchip on 23 Mar 2014 05:28 UTC**

**Comment by nodchip** [comment]
**Modified by nodchip on 23 Mar 2014 07:07 UTC**

**Comment by nodchip** [comment]
**Modified by nodchip on 23 Mar 2014 07:07 UTC**
